@startuml

' CARS company
class CARS
class "Parking site" as ParkingSite
class Address
class Employee
class Car
class "Car model" as CarModel
CARS o-- "*" ParkingSite
CARS -- "*" CarModel : offers >
ParkingSite -- "*" Car : is parked in <
ParkingSite -- "*" Employee : works in <
ParkingSite -- Address : located at >
Car "*" -- CarModel : describes <
Car : +Tag
CarModel : +ID
CarModel : +Type
CarModel : +Number of seats
ParkingSite : +ID
Address : +City
Address : +Type
Address : +Name
Employee : +ID
Employee : +Name
Employee : +Surname

' Insurances
class Insurer
class Insurance
Insurance "*" -- Insurer : provides <
Insurance "*" -- Car : covered by <
Insurer : +ID
Insurer : +Name
Insurance : +Type

' Customer
class Customer
class "Driver license" as DriverLicense
class "Credit card" as CreditCard
Customer -- DriverLicense
Customer -- CreditCard
Customer : +SSN
Customer : +Name
Customer : +Surname
DriverLicense : +ID
DriverLicense : +Expiration date
CreditCard : +Number
CreditCard : +Expiration date

' Reservation
class Reservation
Reservation "*" -- Customer : reserves <
Reservation "*" -- Car : reserves >
Reservation : +Start date
Reservation : +End date

' Check-out - Part 1
class Contract
class Payment
Contract "*" -- Customer : signs <
Contract "0..1" -- "0..1" Reservation : relative to >
Contract -- Payment : has payment >
Contract "*" -- Car : assigned to <
Contract : +ID
Contract : +Start date
Contract : +End date
Contract : +Customer's signature
Payment : +Damage deposit
Payment : +Partial fee
Payment : +Total fee

' Check-out - Part 2
class "Check-out" as Checkout
class Damage
Checkout -- Contract : attached to >
Checkout -- "*" Damage : has >
Checkout "*" -- Customer : signs <
Checkout "*" -- Employee : performs <
Checkout : +Customer's signature
Damage : +Description

' Check-in
class "Check-in" as Checkin
Checkin -- Contract : relative to >
Checkin -- "*" Damage : has new >
Checkin : +End date

' Invoice
class Invoice
Invoice -- Payment : related to >
Invoice : +ID

@enduml
